name: Build and Release Go Binary (Windows)

permissions:
  contents: write
  packages: write

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.23.2'

      - name: Build WS Windows binary
        shell: pwsh
        run: |
          cd ./cmd/SimpleWebsocketForBinary
          $env:GOOS = "windows"
          $env:GOARCH = "amd64"
          go build -o CS2_GameStateIntegration-WSInterface.exe

      - name: Build BombTimer Windows binary
        shell: pwsh
        run: |
          cd ./cmd/BombTimer
          $env:GOOS = "windows"
          $env:GOARCH = "amd64"
          go build -o CS2_GameStateIntegration-BombTimer.exe

      - name: Upload all binaries to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./cmd/SimpleWebsocketForBinary/CS2_GameStateIntegration-WSInterface.exe
            ./cmd/BombTimer/CS2_GameStateIntegration-BombTimer.exe
          name: CS2_GameStateIntegration-BombTimer.exe
          tag_name: ${{ github.ref }}
          body: |
            ## CS2_GameStateIntegration-BombTimer.exe Release

            Built from tag ${{ github.ref }}