name: Build and Release Go Binary (Windows)

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.23.2'

      - name: Build Windows binary
        shell: pwsh
        run: |
          cd ./cmd/SimpleWebsocketForBinary
          $env:GOOS = "windows"
          $env:GOARCH = "amd64"
          go build -o CS2_GameStateIntegration.exe

      - name: Upload binary to release
        uses: softprops/action-gh-release@v1
        with:
          files: ./cmd/SimpleWebsocketForBinary/CS2_GameStateIntegration.exe
          name: CS2_GameStateIntegration.exe
          tag_name: ${{ github.ref }}
          body: |
            ## CS2_GameStateIntegration.exe Release

            Built from tag ${{ github.ref }}